---
- name: Capture POST events from Mattermost
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Fix Index.html File
      condition: >
        event.payload.channel_name == "town-square"
        and event.payload.trigger_word == "website-index-fix"
        and event.payload.user_name == "student"
      action:
        run_workflow_template:
          name: DEMO - EDA Restoring Index.html
          organization: Red Hat Training

    - name: Place Website in Operational Status
      condition: >
        event.payload.channel_name == "town-square"
        and event.payload.trigger_word == "website-service-fix"
        and event.payload.user_name == "student"
      action:
        run_workflow_template:
          name: DEMO - EDA Restoring HTTPD Service
          organization: Red Hat Training


    - name: Print event data
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
